<?php

namespace App\Exports;
use App\Models\Produtos;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStrictNullComparison;

class ProdutosExport implements FromCollection, WithHeadings,WithStrictNullComparison
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        return Produtos::select(
        "id",
        "unidade",
        "prvenda",
        "observacoes",
        "codbarras",
        "patrimonio",
        "emprestados",
        "ativo",
        "npatrimonio",
        "marca",
        "estoque",
        "estoque2",
        "estoque3",
        "estoque4",
        "estoque5",
        "estoque6",
        "minimo",
        "minimo2",
        "minimo3",
        "minimo4",
        "minimo5",
        "minimo6",
        "grupo",
        "consignado",
        "origemconsig",
        "localizacao",
        "codfabricante",
        "maximo1",
        "maximo2",
        "maximo3",
        "maximo4",
        "maximo5",
        "maximo6",
        "idtipo",
        "idseq",
        "idseq_auto",
        "estoque_em_lotes",
        "lote_minimo",
        "lote_maximo",
        "valor_menor",
        "valor_maior",
        "valor_ultimo",
        "regms",
        "bula",
        "pop",
        "nserie",
        "modelo",
        "conferido",
        "dataafericao" ,
        "ncertificado",
        "proafericao" ,
        "datacadastro",
        "epi",
        "validade" ,
        "certificado",
        "validade_epi" ,
        "localizacao2",
        "nome",
        "localizacao3",
        "localizacao4",
        "localizacao5",
        "localizacao6",
        "emprestados1",
        "emprestados2",
        "emprestados3",
        "emprestados4",
        "emprestados5",
        "emprestados6",
        "estoque_comprado",
        "created_at",
        "updated_at")->get();
    }
    /**
     * Write code on Method
     *
     * @return response()
     */
    public function headings(): array
    {
        return [
        "id",
        "unidade",
        "prvenda",
        "observacoes",
        "codbarras",
        "patrimonio",
        "emprestados",
        "ativo",
        "npatrimonio",
        "marca",
        "estoque",
        "estoque2",
        "estoque3",
        "estoque4",
        "estoque5",
        "estoque6",
        "minimo",
        "minimo2",
        "minimo3",
        "minimo4",
        "minimo5",
        "minimo6",
        "grupo",
        "consignado",
        "origemconsig",
        "localizacao",
        "codfabricante",
        "maximo1",
        "maximo2",
        "maximo3",
        "maximo4",
        "maximo5",
        "maximo6",
        "idtipo",
        "idseq",
        "idseq_auto",
        "estoque_em_lotes",
        "lote_minimo",
        "lote_maximo",
        "valor_menor",
        "valor_maior",
        "valor_ultimo",
        "regms",
        "bula",
        "pop",
        "nserie",
        "modelo",
        "conferido",
        "dataafericao" ,
        "ncertificado",
        "proafericao" ,
        "datacadastro",
        "epi",
        "validade" ,
        "certificado",
        "validade_epi" ,
        "localizacao2",
        "nome",
        "localizacao3",
        "localizacao4",
        "localizacao5",
        "localizacao6",
        "emprestados1",
        "emprestados2",
        "emprestados3",
        "emprestados4",
        "emprestados5",
        "emprestados6",
        "estoque_comprado",
        "created_at",
        "updated_at"];
    }
}
