<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produtos extends Model
{
    protected $table = 'materias';

    protected $fillable = [
        'unidade',
        'prvenda',
        'observacoes',
        'codbarras',
        'patrimonio',
        'emprestados',
        'ativo',
        'npatrimonio',
        'marca',
        'estoque',
        'estoque2',
        'estoque3',
        'estoque4',
        'estoque5',
        'estoque6',
        'minimo',
        'minimo2',
        'minimo3',
        'minimo4',
        'minimo5',
        'minimo6',
        'grupo',
        'consignado',
        'origemconsig',
        'localizacao',
        'codfabricante',
        'maximo1',
        'maximo2',
        'maximo3',
        'maximo4',
        'maximo5',
        'maximo6',
        'idtipo',
        'idseq',
        'idseq_auto',
        'estoque_em_lotes',
        'lote_minimo',
        'lote_maximo',
        'valor_menor',
        'valor_maior',
        'valor_ultimo',
        'regms',
        'bula',
        'pop',
        'nserie',
        'modelo',
        'conferido',
        'dataafericao' ,
        'ncertificado',
        'proafericao' ,
        'datacadastro',
        'epi',
        'validade' ,
        'certificado',
        'validade_epi' ,
        'localizacao2',
        'nome',
        'localizacao3',
        'localizacao4',
        'localizacao5',
        'localizacao6',
        'emprestados1',
        'emprestados2',
        'emprestados3',
        'emprestados4',
        'emprestados5',
        'emprestados6',
        'estoque_comprado',
        'created_at',
        'updated_at'
    ];

}
